name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with: 
          # module: qtwidgets # this is here because I thought that there is a missing module
          arch: 'win64_mingw81'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Clean the build
        run: sh ./.github/scripts/clean.sh

      - name: Create a deployment
        run: sh ./.github/scripts/deploy.sh ${{ github.run_number }}

      - name: Add deployment folder to artefacts
        uses: actions/upload-artifact@v2
        with: 
          name: deployment-${{ github.run_number }}
          path: ./deployment-${{ github.run_number }}